version: '3'

services:
  webserver:
    image: nginx:1-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../src:/usr/share/nginx/html
